### ISSUE TITLE
don't put test app inside of extension

### ISSUE THREAD

**Issue by nothingismagick** [kpapro/app-extension-firebase-authentication#2]
because you'll be publishing the app extension to NPM, there is no reason to do it this way. I generally have two folders:
```
/%_extension-name_%
   /extension  // <= this gets npm published
   /test-extension // <= this uses yarn link to test the extension
```

**Comment by adamkpurdy** [comment]
Addressed with https://github.com/kpapro/app-extension-firebase-authentication/commit/b657b3259775cae942fcb8b916baf57be06e101f
