### ISSUE TITLE
Create the routes for the user

### ISSUE THREAD

**Issue by nothingismagick** [kpapro/app-extension-firebase-authentication#3]
I think that extensions should be turnkey as much as possible, aka make them plug-and-play. Therefore the advice to "copypasta" routes seems to me to be asking them to do something... Know what I mean?

**Comment by adamkpurdy** [comment]
I do, and I'm curious as to to the solution for this. I know the install script is the place to start, but how do you determine what a user actually wants for a route structure, and then in turn writing the script to read the routes file, and extend it.

**Comment by nothingismagick** [comment]
Sure, I mean whatever works. And I don't have an easy answer for you here. I think that some serious thought needs to go into it.

**Comment by adamkpurdy** [comment]
On one hand, not many people will start an app without authentication, but I'm gonna try and put a wrap on this after I get some e2e and some jest in the test app. Then I was going to ask for some guidance on a roadmap for this extension. 

The route file was at the top of my list, but I'm a little hesitant as I think these extension will probably be a good jump off point for people, and then inevitably people will tweak to their own desires.

Going to close this. Thanks for your feed back.
